
MathJax.Hub.Config({
    TeX: {
        Macros: {
            rhozero: '{\\rho_0}',
            pizero: '{\\pi_0}',
            pizeroone: '{\\pi_0^{(1)}}',
            pizerotwo: '{\\pi_0^{(2)}}',
            gammabar: '{\\overline{\\Gamma}_1}',
            ptl: '{{\\partial}}',
            eb: '{{\\bf e}}',
            fb: '{{\\bf f}}',
            ib: '{{\\bf i}}',
            Ub: '{{\\bf U}}',
            Vb: '{{\\bf V}}',
            xb: '{{\\bf x}}',
            ut: '{\\tilde{u}}',
            vt: '{\\tilde{v}}',
            wt: '{\\tilde{w}}',
            Ubt: '{\\widetilde{\\Ub}}',
            edge: '{\\rm EDGE}',
            mac: '{\\rm MAC}',
            trans: '{\\rm TRANS}',
            nablab: '{\\mathbf{\\nabla}}',
            cdotb: '{\\mathbf{\\cdot}}',
            half: '{\\frac{1}{2}}',
            myhalf: '{\\frac{1}{2}}',
            nph: '{{n + \\myhalf}}',
            nmh: '{{n - \\myhalf}}',
            Hext: '{{H_{\\rm ext}}}',
            Hnuc: '{{H_{\\rm nuc}}}',
            kth: '{k_{\\rm th}}',
            pred: '{{\\rm pred}}',
            Sbar: '{\\overline{S}}',
            inp: '{\\mathrm{in}}',
            initp: '{\\mathrm{init}}',
            outp: '{\\mathrm{out}}',
            uadv: '{\\widetilde{\\mathbf{U}}^{\\mathrm{ADV}}}',
            uadvone: '{\\widetilde{\\mathbf{U}}^{\\mathrm{ADV},\\star}}',
            uadvonedag: '{\\Ubt^{\\mathrm{ADV},\\dagger,\\star}}',
            uadvtwo: '{\\widetilde{\\mathbf{U}}^{\\mathrm{ADV}}}',
            uadvtwodag: '{\\Ubt^{\\mathrm{ADV},\\dagger}}',
            uadvsdcstar: '{\\mathbf{U}^{\\mathrm{ADV},\\star}}',
            uadvsdcpred: '{\\mathbf{U}^{\\mathrm{ADV},\\mathrm{pred}}}',
            uadvsdc: '{\\mathbf{U}^{\\mathrm{ADV}}}',
            dt: '{\\Delta t}',
            dr: '{\\Delta r}',
            etarho: '{\\eta_{\\rho}}',
            etarhoec: '{\\etarho^{\\rm ec}}',
            etarhocc: '{\\etarho^{\\rm cc}}',
            etarhoflux: '{\\etarho^{\\rm flux}}',
            divetarho: '{\\nabla\\cdot(\\etarho\\eb_r)}',
            ow: '{\\overline{w}_0}',
            dw: '{\\delta w_0}',
            thalf: '{\\sfrac{3}{2}}',
            rhop: '{{\\rho^{\\prime}}}',
            omegadot: '{\\dot{\\omega}}',
            er: '{\\mathbf{e}_r}',
            ex: '{\\mathbf{e}_x}',
            ey: '{\\mathbf{e}_y}',
            ez: '{\\mathbf{e}_z}',
            Omegab: '{{\\bf \\Omega}}',
            rb: '{{\\bf r}}',
            isotm: ['{{}^{#2}\\mathrm{#1}}', 2],
            edot: '{{{\\dot{e}_\\mathrm{nuc}}}}',
            enuc: '{{{{e}_\\mathrm{nuc}}}}',
            edotnu: '{{{\\dot{e}_\\nu}}}',
            rt: '{\\tilde{r}_0}',
            rhob: '{\\ensuremath{\\rho_\\mathrm{base}}}',
            Tb: '{\\ensuremath{T_\\mathrm{base}}}',
            gcc: '{\\mathrm{g~cm^{-3} }}',
            pb: '{p_\\mathrm{base}}',
            qburn: '{q_\\mathrm{burn}}',
            Uc: '{{\\boldsymbol{\\mathcal{U}}}}',
            Fb: '{\\mathbf{F}}',
            Sc: '{\\mathbf{S}}',
            Shydro: '{{{\\bf S}^{\\mathrm{hydro}}}}',
            Rb: '{{\\bf R}}',
            Rq: '{{\\bf R}}',
            Adv: ['{{\\left [\\mathcal{A} \\left(#1\\right)\\right]}}', 1],
            Advs: ['{{\\mathcal{A} \\left(#1\\right)}}', 1],
            Sdot: '{\\dot{S}}',

        }
    }
});

