PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 3

COMP	   = gnu

USE_MPI    = FALSE
USE_OMP    = FALSE

EBASE = main

EXTERN_SEARCH += .

CUVODE_HOME = ../.

Bpack   := ./Make.package
Blocs   := .

include $(CUVODE_HOME)/Make.cuVODE


