&PROBIN
  test_set = "gr0_3d.small"

  dens_min   = 1.d-3
  dens_max   = 5.d9
  temp_min   = 1.d7
  temp_max   = 5.d8 ! Note that BS fails at 1d9+

  tmax = 1.0d-1

  xin_file   = "xin.reaclib_cburn"
  run_prefix = "react_reaclib_cburn_"

  burner_verbose = .false.

  ! Set which jacobian to use
  ! 1 = analytic jacobian
  ! 2 = numerical jacobian
  jacobian   = 1

  ode_max_steps = 100000
  scaling_method = 1
  retry_burn = .false.
  renormalize_abundances = .false.

  rtol_spec = 1.0d-9
  rtol_enuc = 1.0d-6
  rtol_temp = 1.0d-6
  atol_spec = 1.0d-9
  atol_enuc = 1.0d-6
  atol_temp = 1.0d-6
  
/
