PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 3

COMP	   = gnu

USE_MPI    = FALSE
USE_OMP    = FALSE

EBASE = main

EXTERN_SEARCH += .

SDC_HOME = ../.

Bpack   := ./Make.package
Blocs   := .

include Make.SDC


