name: check PR branch

on: [pull_request]
jobs:
  check-PR-branch:
    runs-on: ubuntu-latest
    steps:
      - name: PRs should not target main
        run: |
          if [[ "${{ github.event.pull_request_target.head.ref }}" == "main" ]]; then
            echo "Pull requests must not be made against main. Please target development instead."
            exit 1
          fi
