name: check PR branch

on: [pull_request]
jobs:
  check-PR-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth 0

      - name: Get PR target branch
        id: get-target-branch
        run: bash .github/workflows/get_pr_target_branch.sh

      - name: No PRs should target the main branch; use development instead
        if: ${{ steps.get-target-branch.outputs.target_branch == 'main' }}
        run: exit 1
