name: "clang-tidy"

on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  clang_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Get AMReX
        run: |
          git clone --branch development --depth 1 https://github.com/AMReX-Codes/amrex.git external/amrex
          echo "AMREX_HOME=${GITHUB_WORKSPACE}/external/amrex" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          .github/workflows/dependencies_clang-tidy-apt-llvm.sh 19

      - name: Compile burn_cell_sdc
        run: |
          cd unit_test/burn_cell_sdc
          make USE_MPI=FALSE USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-19 CLANG_TIDY_WARN_ERROR=TRUE -j 4
