name: github pages

on:
  push:
    branches:
      - main
      - development

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pandoc and doxygen
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: "pip"

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Build docs
        env:
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: ./deploy_docs_action.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true
