name: jac_cell

on: [pull_request]
jobs:
  jac_cell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Get AMReX
        run: |
          git clone --branch development --depth 1 https://github.com/AMReX-Codes/amrex.git external/amrex
          echo "AMREX_HOME=${GITHUB_WORKSPACE}/external/amrex" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++

      - name: Compile jac_cell
        run: |
          cd unit_test/jac_cell
          make -j 4

      - name: Run jac_cell
        run: |
          cd unit_test/jac_cell
          ./main3d.gnu.ex inputs > test.out

      - name: Compare to stored output
        run: |
          cd unit_test/jac_cell
          diff -I "^Initializing AMReX" -I "^AMReX"  test.out ci-benchmarks/jac_cell_aprox13.out
