name: jac_cell

on: [pull_request]
jobs:
  nse_table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile jac_cell
        run: |
          cd unit_test/jac_cell
          make -j 4

      - name: Run jac_cell
        run: |
          cd unit_test/jac_cell
          ./main3d.gnu.ex inputs > test.out

      - name: Compare to stored output
        run: |
          cd unit_test/jac_cell
          diff -I "^Initializing AMReX" -I "^AMReX"  test.out ci-benchmarks/jac_cell_aprox13.out



